# Generated by Django 5.1.1 on 2024-09-15 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(help_text='Channel for connected player', max_length=255)),
                ('last_seen', models.DateTimeField(default=datetime.datetime(2024, 9, 15, 19, 20, 41, 702905, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(help_text='Unique identifier for a channel room.', max_length=255, unique=True)),
            ],
        ),
    ]
