# Generated by Django 5.1.2 on 2024-10-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_player_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaRoom',
            fields=[
            ],
            options={
                'db_table': 'room',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.room',),
        ),
    ]
