# Generated by Django 5.1.1 on 2024-10-06 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 21, 7, 43, 696933, tzinfo=datetime.timezone.utc)),
        ),
    ]
