version: "3.12"

services:
  src:
    build:
      context: .
      args: 
        - DEV=true
    ports:
      - 8000:8000
    volumes:
      - ./src:/src
    command: >
      sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - ROOM_SIZE_THRESHOLD=${ROOM_SIZE_THRESHOLD}
      - TESTING=${TESTING}
    depends_on: 
      - db
    
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - dev-db-data:/var/lib/pgsql/data

  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis/data
      - redis-conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASS}
      - REDIS_DATABASES=${REDIS_DATABASES}


volumes:
  dev-db-data:
  redis-data:
  redis-conf:

