# Generated by Django 5.1.2 on 2024-10-20 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 20, 16, 8, 12, 490018, tzinfo=datetime.timezone.utc)),
        ),
    ]
